### ISSUE TITLE
Unsure what is wrong...

### ISSUE THREAD

**Issue by garmcqui** [jardous/tof_vl53l1x#1]
Hi, I am using the custom component in my YAML for a sensor, and it has been working great for 5 months until recently, when I start getting errors on installing.  Please see the attached log file.  Any advice appreciated.  

[logs_oiltank_upload.txt](https://github.com/jardous/tof_vl53l1x/files/8390720/logs_oiltank_upload.txt)

**Comment by Scoff123** [comment]
I am also now seeing this also. I have been using this custom component in my Home Assistant for just a couple of weeks and it has been working fine. I have tried recompiling and flashing my Lolin D1 Mini Pro with my latest yaml following a couple of 
small changes in my code, however now I am receiving the same issue as posted above. 

Upon compiling, I am seeing the following error:

![image](https://user-images.githubusercontent.com/96984460/161583916-d0df17fe-0e72-470d-b8ce-d04ef2c872ed.png)

log file attached 

[logs_oiltank_upload.txt](https://github.com/jardous/tof_vl53l1x/files/8411745/logs_oiltank_upload.txt)

**Comment by Scoff123** [comment]
also attaching the current version of vl53l1x.h file being referenced in my ESPHome setup
[vl53l1x_h.txt](https://github.com/jardous/tof_vl53l1x/files/8411760/vl53l1x_h.txt)

**Comment by jardous** [comment]
Sorry guys. I do not use ESPHome since years and I do not plan to provide any support here.
